server:
  port: ${PORT:8084}
  servlet:
    context-path: ${CONTEXT_PATH:/instances/kotlin/1}
logging:
  level:
    org:
      springframework:
        web: info
      apache: info
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown, health

